import { Translations, Language } from '../types';

export const translations: Translations = {
  [Language.EN]: {
    loginAs: "Login as",
    // User Roles
    student: "Student",
    learner: "Learner",
    entrepreneur: "Entrepreneur",
    employer: "Employer",
    trainer: "Trainer",
    funder: "Funder",
    implementer: "Implementer",
    mentor: "Mentor",
    coach: "Coach",
    facilitator: "Facilitator",
    partner_facilitator: "Partner Facilitator",
    publisher: "Publisher",
    editor: "Editor",
    producer: "Producer",
    artist: "Artist",
    hr_business_partner: "HR business partner",
    hr_officer: "HR officer",
    recruiter: "Recruiter",
    payroll_specialist: "Payroll specialist",
    team_lead: "Team lead",
    alumni: "Alumni",
    intern: "Intern",
    supervisor: "Supervisor",
    manager: "Manager",
    administrator: "Administrator",
    super_administrator: "Super Administrator",
    // Role Categories
    youth: "Youth",
    entrepreneur_category: "Entrepreneurship & Partnerships",
    contributor_category: "Contributor",
    staff_category: "Staff",
    hr_staff_category: "HR & team leadership",
    super_admin_category: "Super Administrator",

    login: "Login",
    dashboard: "Dashboard",
    courses: "Courses",
    jobs: "Jobs",
    settings: "Settings",
    logout: "Logout",
    welcome: "Welcome",
    dashboard_title: "Your Dashboard",
    dashboard_subtitle: "Here's an overview of your activity.",
    dashboard_week: "Week",
    dashboard_month: "Month",
    dashboard_no_data_period: "No data for this period",
    dashboard_hours: "Hours",
    no_recent_activity: "No recent activity",
    view_all: "View all",
    my_courses: "My Courses",
    view_all_courses: "View All Courses",
    job_openings: "Job Openings",
    view_all_jobs: "View All Jobs",
    settings_title: "Settings",
    language: "Language",
    english: "English",
    french: "French",
    profile: "Profile",
    senegel_workflow_platform: "COYA",
    course_duration: "Duration",
    course_progress: "Progress",
    job_posted: "Posted",
    job_type: "Type",
    job_location: "Location",
    projects: "Projects",
    project_management_title: "Intelligent Project Management",
    project_management_subtitle: "Create, manage, and track your projects with AI-powered assistance.",
    new_project: "New Project",
    create_project: "Create Project",
    project_title: "Project Title",
    project_description: "Project Description",
    due_date: "Due Date",
    team_members: "Team Members",
    selected_team_members: "Selected Team Members",
    add_team_members: "Add Team Members",
    loading_users: "Loading users",
    no_users_found: "No users found",
    no_users_available: "No users available",
    delete_project: "Delete Project",
    confirm_delete_project: "Are you sure you want to delete this project? This action cannot be undone.",
    status: "Status",
    not_started: "Not Started",
    in_progress: "In Progress",
    completed: "Completed",
    tasks: "Tasks",
    to_do: "To Do",
    done: "Done",
    generate_tasks_with_ai: "Generate Tasks with AI",
    image_generator: "Image Generator",
    image_generator_subtitle: "Create stunning images from text descriptions. Powered by Imagen.",
    image_prompt_placeholder: "e.g., A vibrant market scene in Dakar with futuristic elements",
    generate_image: "Generate Image",
    generating: "Generating...",
    my_skills: "My Skills (Skill Passport)",
    skill_passport_subtitle: "This helps us match you with the right jobs and projects.",
    add_skill: "Add Skill",
    enter_skill: "Enter a skill...",
    my_job_postings: "My Job Postings",
    applicants: "Applicants",
    no_applicants: "No applicants yet.",
    view_applicants: "View Applicants",
    apply_now: "Apply Now",
    applied: "Applied",
    ai_smart_match: "AI Smart Match",
    top_candidate: "Top Candidate",
    my_projects: "My Projects",
    view_all_projects: "View All Projects",
    course_detail: "Course Detail",
    back_to_courses: "Back to Courses",
    modules: "Modules",
    lessons: "Lessons",
    start_learning: "Start Learning",
    continue_learning: "Continue Learning",
    course_management: "Course Management",
    course_management_subtitle: "Create, edit, and organize all courses on the platform.",
    add_new_course: "Add New Course",
    edit_course: "Edit Course",
    analytics: "Analytics",
    platform_analytics: "Platform Analytics",
    platform_analytics_subtitle: "Key metrics and insights into platform activity.",
    user_growth: "User Growth",
    enrollment_trends: "Enrollment Trends",
    job_application_funnel: "Job Application Funnel",
    view_talent_analytics: "View Talent Analytics",
    talent_analytics: "Talent Analytics",
    talent_analytics_subtitle: "Insights into the skills and potential of our user base.",
    back_to_analytics: "Back to Analytics",
    skill_gap_analysis: "Skill Gap Analysis",
    most_demanded_skills: "Most Demanded Skills (from Job Postings)",
    available_skills: "Top Available Skills (from User Passports)",
    talent_forecasting: "Talent Forecasting",
    talent_forecasting_subtitle: "Use AI to predict future talent needs and availability.",
    forecast_needs: "Forecast Needs",
    goals_okrs: "Goals (OKRs)",
    risk_management: "Risk Management",
    crm_sales: "CRM & Sales",
    knowledge_base: "DOCS SENEGEL",
    goals_okrs_title: "Strategic Goal Alignment (OKRs)",
    goals_okrs_subtitle: "Define and track Objectives and Key Results for your projects.",
    select_project: "Select a Project",
    generate_okrs_with_ai: "Generate OKRs with AI",
    objective: "Objective",
    key_results: "Key Results",
    ai_okr_suggestions: "AI-generated OKR Suggestions",
    add_to_project: "Add to project",
    risk_management_tab: "Risk Management",
    identify_risks_with_ai: "Identify Risks with AI",
    likelihood: "Likelihood",
    impact: "Impact",
    mitigation_strategy: "Mitigation Strategy",
    high: "High",
    medium: "Medium",
    low: "Low",
    priority: "Priority",
    assignee: "Assignee",
    unassigned: "Unassigned",
    time_tracking: "Time Tracking",
    log_time: "Log Time",
    generate_status_report: "Generate Status Report",
    summarize_tasks: "Summarize Tasks",
    crm_title: "Customer Relationship Management",
    crm_subtitle: "Manage your contacts and sales pipeline.",
    crm_kpi_total_contacts: "Total contacts",
    crm_kpi_leads: "Leads",
    crm_kpi_prospects: "Prospects",
    crm_kpi_customers: "Customers",
    crm_kpi_conversion: "Conversion",
    draft_email_with_ai: "Draft Email with AI",
    crm_permission_denied: "You do not have permission to perform this action on this contact.",
    crm_default_sales_context: "Introduce our services and propose a short discovery call.",
    crm_draft_email_title: "Email draft",
    crm_draft_ai_error: "AI could not generate the email. You can use the template below or copy your own text.",
    crm_draft_fallback_body: "Hello,\n\nWe would be glad to discuss how we can support your organization.\n\nKind regards",
    crm_email_copy: "Copy text",
    crm_email_open_mail: "Open mail app",
    crm_email_close: "Close",
    crm_email_copy_ok: "Copied to clipboard",
    crm_email_copy_fail: "Copy failed",
    crm_persist_failed: "The contact could not be saved on the server; the data collection was not linked.",
    crm_filter_campaign_origin: "Campaign origin",
    crm_filter_all_campaigns: "All campaigns",
    crm_column_collecte: "Collection",
    crm_badge_collecte: "Collection",
    crm_import_submissions: "Import submissions",
    crm_collecte_enrich_modal_title: "Link collection to CRM",
    crm_collecte_enrich_modal_body:
      "Prefer syncing real submissions (bulk) from the Collecte module so each contact carries campaign and submission IDs. You can still create a single placeholder contact for visibility.",
    crm_collecte_placeholder_note: "Secondary: placeholder contact (fictitious email)",
    crm_open_collecte: "Open Collecte workspace (this CRM)",
    crm_search_contacts_placeholder: "Search by name, company or email…",
    crm_hide_placeholder_emails: "Hide collection placeholder emails",
    collecte_submissions_synced_ratio: "Synced to CRM",
    collecte_open_in_crm: "Open in CRM (filtered)",
    crm_enrich_from_collecte: "Enrich from collection",
    crm_tab_collecte: "Collecte & imports",
    crm_collecte_hub_title: "Collecte in the CRM",
    crm_collecte_hub_subtitle:
      "Monitor local campaigns, submissions, sync status and CRM contacts originating from Collecte — without leaving this module.",
    crm_collecte_sync_all_pending: "Sync all pending submissions",
    crm_collecte_sync_result: "Sync completed",
    crm_collecte_sync_skipped: "skipped or failed",
    crm_collecte_kpi_submissions: "Submissions",
    crm_collecte_kpi_pending: "Pending sync",
    crm_collecte_kpi_synced_local: "Synced (local)",
    crm_collecte_kpi_crm_from_collecte: "CRM contacts (Collecte)",
    crm_collecte_campaigns_title: "Campaigns",
    crm_collecte_empty_campaigns: "No local campaigns for this organisation. Use the « Collecte & imports » tab in this CRM screen to create one.",
    crm_collecte_badge_linked: "Marked CRM link",
    crm_collecte_row_submissions: "Submissions",
    crm_collecte_row_pending: "Pending",
    crm_collecte_row_crm: "In CRM",
    crm_collecte_action_filter_crm: "Filter contacts",
    crm_collecte_action_open_collecte: "Preset in Collect tab (this CRM)",
    crm_collecte_action_sync_campaign: "Sync this campaign",
    crm_webhook_card_title: "Signed HTTP webhooks (server relay)",
    crm_webhook_card_body:
      "Events (contact created/updated, Collecte sync) are POSTed by a Supabase Edge Function with header X-Coya-Signature: sha256=<hmac>. Configure HTTPS URLs here; the signing secret is shown only once when created or regenerated.",
    crm_webhook_no_org: "No organisation is attached to your profile — webhooks cannot be configured.",
    crm_webhook_error_https: "URL must start with https://",
    crm_webhook_confirm_delete: "Delete this webhook endpoint?",
    crm_webhook_confirm_regenerate: "Regenerate signing secret? The previous secret will stop working immediately.",
    crm_webhook_secret_once: "Copy this signing secret now. It will not be shown again in the list.",
    crm_webhook_secret_dismiss: "Hide",
    crm_webhook_add_title: "New endpoint",
    crm_webhook_url_placeholder: "https://example.com/hooks/coya",
    crm_webhook_label_placeholder: "Label (optional, e.g. n8n production)",
    crm_webhook_add_button: "Add webhook",
    crm_webhook_list_title: "Configured endpoints",
    crm_webhook_refresh: "Refresh",
    crm_webhook_empty: "No webhook yet. Add an HTTPS URL to receive signed CRM payloads.",
    crm_webhook_last: "Last delivery",
    crm_webhook_never: "Never delivered",
    crm_webhook_disable: "Disable",
    crm_webhook_enable: "Enable",
    crm_webhook_regenerate: "New secret",
    crm_webhook_delete: "Delete",
    crm_webhook_ping: "Test delivery",
    crm_webhook_ping_ok: "Relay invoked (check target and last delivery status).",
    crm_webhook_ping_fail: "Test failed",
    crm_webhook_readonly: "Only managers and administrators can change webhook settings.",
    crm_collecte_enrich_modal_empty_hint:
      "No eligible campaign. Create one in the CRM tab « Collecte & imports » (workshop below), then return here.",
    crm_dossier_badge: "Client file",
    crm_dossier_col: "File",
    crm_dossier_open: "Open client file (history, notes, links)",
    crm_dossier_open_short: "File",
    crm_dossier_tab_timeline: "Timeline",
    crm_dossier_tab_notes: "Notes",
    crm_dossier_tab_files: "Links & files",
    crm_dossier_empty_timeline: "No entries yet. Changes to the contact are logged automatically when saved.",
    crm_dossier_empty_notes: "No notes yet.",
    crm_dossier_empty_files: "No links or file references yet.",
    crm_dossier_add_note: "Add a note",
    crm_dossier_note_title_ph: "Title",
    crm_dossier_note_body_ph: "Detail (optional)",
    crm_dossier_save_note: "Save note",
    crm_dossier_add_link: "Add external link",
    crm_dossier_link_title_ph: "Link label",
    crm_dossier_save_link: "Save link",
    crm_dossier_add_file_ref: "File / contract (URL or storage link)",
    crm_dossier_file_label_ph: "Document name",
    crm_dossier_file_url_ph: "https://… or storage path",
    crm_dossier_save_file_ref: "Save reference",
    crm_dossier_confirm_delete: "Delete this dossier entry?",
    crm_contact_detail_back: "Back to list",
    crm_contact_detail_title: "Contact record",
    crm_contact_detail_edit: "Edit",
    crm_contact_detail_delete: "Delete",
    crm_contact_detail_draft_email: "AI email draft",
    crm_contact_detail_section_crm: "CRM information",
    crm_contact_detail_section_collecte: "Collecte (submission)",
    crm_contact_detail_collecte_submitted_at: "Submitted:",
    crm_contact_detail_collecte_no_local:
      "No local submission is linked to this contact (browser storage). CRM fields above still hold synced data; open Collecte to manage campaigns.",
    crm_contact_detail_collecte_empty_payload: "Submission exists but the payload is empty.",
    crm_contact_detail_go_collecte: "Open campaign in Collecte tab",
    crm_contact_detail_source: "Source",
    crm_contact_detail_created_by: "Created by",
    crm_contact_detail_notes: "Notes",
    crm_contact_detail_tags: "Tags",
    crm_contact_detail_not_found: "This contact is no longer in the list.",
    crm_integrations_title: "Integrations & partner apps",
    crm_integrations_body:
      "Outbound events are broadcast to registered handlers and to window.__COYA_CRM_EVENT__ for external web apps (iframe, browser extension, or reverse proxy). Use this to mirror contacts, syncs and automations in another stack.",
    knowledge_base_title: "DOCS SENEGEL",
    knowledge_base_subtitle: "Document library: folders with access control (owner + invited viewers/editors), Office and PDF files.",
    daf_services: "General services & DAF",
    daf_services_title: "General services & DAF requests",
    daf_services_subtitle: "Submit internal requests (supplies, logistics, IT, vehicles, etc.) to the administrative and finance department.",
    daf_new_request: "New request",
    daf_my_requests: "My requests",
    daf_category: "Category",
    daf_status: "Status",
    daf_title_field: "Title",
    daf_description: "Description",
    daf_submit: "Submit",
    daf_save_draft: "Save draft",
    daf_daf_comment: "DAF comment",
    daf_intro_workflows:
      "Choose a workflow: general request, official documents to be delivered, information answer (text, link or file), or a signature cycle (upload, send for signature, receive signed file).",
    daf_request_kind: "Workflow type",
    daf_request_kind_help:
      "Document delivery: DAF attaches the files to provide. Information: DAF replies with text, link and/or attachment. Signature: attach the document to sign, track external signing, then attach the signed return.",
    daf_queue_org: "Organisation queue (DAF / managers)",
    daf_empty_list: "No requests yet.",
    daf_open_detail: "Open",
    daf_close_detail: "Close",
    daf_status_draft: "Draft",
    daf_status_submitted: "Submitted",
    daf_status_in_review: "In review",
    daf_status_awaiting_requester: "Awaiting requester",
    daf_status_pending_external_signature: "Pending external signature",
    daf_status_approved: "Approved",
    daf_status_rejected: "Rejected",
    daf_status_fulfilled: "Completed",
    daf_status_cancelled: "Cancelled",
    daf_kind_general: "General",
    daf_kind_document_delivery: "Document delivery",
    daf_kind_information: "Information / answer",
    daf_kind_signature_workflow: "Signature workflow",
    daf_wf_hint_general: "Standard processing: take in charge, approve, reject or close when done.",
    daf_wf_hint_document: "DAF attaches official documents, then closes the request when delivered.",
    daf_wf_hint_information: "DAF posts a reply (message, link, optional file). Close when the requester has what they need.",
    daf_wf_hint_signature: "Attach the file to sign, mark when sent for signature, then attach the signed return and close.",
    daf_signature_phase: "Signature phase",
    daf_phase_none: "Not started",
    daf_phase_original_provided: "Original provided",
    daf_phase_sent_for_signature: "Sent for signature",
    daf_phase_signed_returned: "Signed file received",
    daf_thread_title: "Conversation",
    daf_thread_empty: "No messages yet.",
    daf_add_message: "Add a message",
    daf_message_placeholder: "Your message…",
    daf_link_placeholder: "Optional link (URL)",
    daf_internal_only: "Internal note (DAF / managers only)",
    daf_post_message: "Post",
    daf_you: "You",
    daf_participant: "Participant",
    daf_internal_note: "internal",
    daf_attachments_title: "Attachments",
    daf_attachments_empty: "No attachments.",
    daf_download: "Download",
    daf_attach_supporting: "Supporting file",
    daf_attach_signature_original: "Document to be signed",
    daf_attach_daf_deliverable: "Document provided",
    daf_attach_info_answer: "Information attachment",
    daf_attach_signature_signed: "Signed return",
    daf_reviewer_actions: "DAF / manager actions",
    daf_action_take_in_review: "Take in charge",
    daf_action_take_ownership: "Assign to me",
    daf_assign_unassigned: "Unassigned",
    daf_assign_me: "Assigned to me",
    daf_assign_other: "Assigned",
    daf_action_await_requester: "Ask requester for more",
    daf_optional_comment: "Comment for requester (optional)",
    daf_upload_deliverable: "Upload the document(s) to deliver to the requester.",
    daf_choose_file: "Choose file",
    daf_action_close_document: "Mark as delivered / closed",
    daf_info_upload_hint: "Optional: attach a file with the information (in addition to the message or link).",
    daf_attach_info_file: "Attach answer file",
    daf_action_close_information: "Close request (information provided)",
    daf_signature_reviewer_hint: "When the document is with the signatory, mark as sent. When the signed PDF is back, upload it here.",
    daf_action_mark_sent_sign: "Marked as sent for signature",
    daf_upload_signed_return: "Upload signed return",
    daf_action_close_after_signature: "Close after signed return",
    daf_action_signed_received: "Signed file received — continue review",
    daf_action_approve: "Approve",
    daf_action_reject: "Reject",
    daf_action_fulfill: "Close / fulfilled",
    daf_requester_reply_hint: "The DAF is waiting for your input.",
    daf_requester_upload_support: "You can attach supporting files, then confirm you have replied.",
    daf_action_requester_done: "I have provided the requested items",
    daf_requester_files: "Your attachments",
    drive_my_drive: "Browse",
    drive_acl_title: "Folder access",
    drive_acl_add: "Invite",
    drive_acl_remove: "Remove",
    drive_acl_permission_viewer: "Viewer",
    drive_acl_permission_editor: "Editor",
    drive_acl_owner: "Owner",
    drive_acl_help: "Only the owner and invited collaborators see this folder and its files. Admins always have access.",
    drive_office_only_hint: "Allowed types: PDF, Word, Excel, PowerPoint and similar.",
    drive_folder_visibility: "Folder visibility",
    drive_folder_visibility_help: "Private = only invited users. Public = visible to the whole organisation.",
    drive_visibility_private: "Private (invited only)",
    drive_visibility_org_public: "Public (organisation)",
    drive_visibility_no_rights: "You don't have rights to change visibility.",
    drive_copy: "Copy",
    drive_cut: "Cut",
    drive_paste: "Paste",
    drive_view_grid: "Grid",
    drive_view_list: "List",
    drive_sort: "Sort",
    drive_sort_name_asc: "Name (A→Z)",
    drive_sort_name_desc: "Name (Z→A)",
    drive_sort_updated_desc: "Modified (newest)",
    drive_sort_updated_asc: "Modified (oldest)",
    drive_sort_created_desc: "Created (newest)",
    drive_sort_created_asc: "Created (oldest)",
    drive_items: "Items",
    drive_empty: "No items.",
    create_doc_from_text: "Create New Document from Text",
    paste_text_here: "Paste your text here (e.g., meeting notes)...",
    summarize_and_create: "Summarize & Create",
    all_documents: "All Documents",
    create_new_job: "Create New Job",
    post_job: "Post Job",
    company_name: "Company Name",
    job_title: "Job Title",
    required_skills: "Required Skills",
    required_skills_placeholder: "e.g., React, Node.js, Marketing (comma-separated)",
    full_time: "Full-time",
    part_time: "Part-time",
    contract: "Contract",
    back_to_jobs: "Back to Jobs",
    user_management: "User Management",
    user_management_subtitle: "View and manage all platform users.",
    name: "Name",
    email: "Email",
    role: "Role",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    search: "Search",
    sort_by_date: "Sort by Date",
    sort_by_title: "Sort by Title",
    sort_by_status: "Sort by Status",
    sort_by_progress: "Sort by Progress",
    sort_by_duration: "Sort by Duration",
    sort_by_entity: "Sort by Entity",
    results_found: "results found",
    total_logs: "Total Logs",
    total_hours: "Total Hours",
    daily_average: "Daily Average",
    all_types: "All Types",
    delete_log: "Delete Log",
    confirm_delete_log_message: "Are you sure you want to delete this time log?",
    entity: "Entity",
    deactivate: "Deactivate",
    no_projects_found: "No projects found. Create one to get started!",
    no_courses_found: "No courses are available at the moment. Please check back later.",
    no_jobs_found: "No job openings found. Check back later or create a new one!",
    save: "Save",
    cancel: "Cancel",
    confirm_delete: "Confirm Delete",
    are_you_sure: "Are you sure?",
    confirm_delete_message: "This action cannot be undone. All associated data will be lost.",
    edit_project: "Edit Project",
    create_new_project: "Create New Project",
    instructor: "Instructor",
    course_icon: "Course Icon (FontAwesome)",
    add_module: "Add Module",
    add_lesson: "Add Lesson",
    edit_objective: "Edit Objective",
    create_objective: "Create Objective",
    delete_objective: "Delete Objective",
    add_key_result: "Add Key Result",
    target: "Target",
    unit: "Unit",
    current_value: "Current",
    create_contact: "Create Contact",
    edit_contact: "Edit Contact",
    delete_contact: "Delete Contact",
    contact_name: "Contact Name",
    contact_company: "Contact Company",
    contact_status: "Status",
    lead: "Lead",
    contacted: "Contacted",
    prospect: "Prospect",
    customer: "Customer",
    unreachable: "Unreachable",
    callback_expected: "Callback expected",
    crm_btn_contacted: "Contacted",
    crm_btn_unreachable: "Unreachable",
    crm_btn_callback: "Callback expected",
    crm_codification_hint:
      "Outreach codification: Contacted = reached; Unreachable = could not reach; Callback expected = follow-up required. Wire webhooks or automations in Settings to notify your team or create tasks.",
    pending_access_title: "Access pending configuration",
    pending_access_body:
      "Your account is active but no department modules are assigned yet, or your permissions have not been finalized. Please contact your Super Administrator.",
    pipeline_view: "Pipeline",
    list_view: "List",
    grid_view: "Grid",
    compact_view: "Compact",
    sort_ascending: "Ascending",
    sort_descending: "Descending",
    view_label: "View",
    objective_found_singular: "objective found",
    objective_found_plural: "objectives found",
    project_found_singular: "project found",
    project_found_plural: "projects found",
    for_search: "for",
    work_email: 'Work Email',
    personal_email: 'Personal Email',
    office_phone: 'Office Phone',
    mobile_phone: 'Mobile Phone',
    whatsapp_number: 'WhatsApp Number',
    assign_role: "Assign Role",
    user_role: "User Role",
    signup_role_label: "Role (platform function)",
    signup_poste_note: "Your job title (poste) can be set later in your profile by an administrator.",
    poste_label: "Job title (position)",
    ai_agent_title: 'COYA AI',
    ai_agent_placeholder: 'Ask me anything...',
    ai_agent_send: 'Send',
    ai_agent_welcome_default: 'Hello! How can I help you today?',
    ai_agent_welcome_dashboard: 'Welcome to your dashboard! Ask me to find a section or summarize your activities.',
    ai_agent_welcome_projects: "In Projects, I can help you brainstorm tasks, identify risks, or draft project plans. What's on your mind?",
    ai_agent_welcome_goals_okrs: "Working on goals? I can help you define clear Objectives and Key Results (OKRs). Ask me how!",
    ai_agent_welcome_courses: "Ready to learn? Ask me to find a course on a specific topic or suggest a learning path.",
    ai_agent_welcome_jobs: "Looking for opportunities? I can help you find jobs that match your skills or give you interview tips.",
    ai_agent_welcome_knowledge_base: "This is DOCS SENEGEL. Ask me to find a file, summarise a document, or suggest a folder structure.",
    ai_agent_welcome_crm_sales: "In the CRM, I can help you draft emails to contacts or suggest ways to manage your sales pipeline.",
    ai_agent_welcome_course_management: "Managing courses? I can help you structure modules, create lesson plans, or write course descriptions.",
    ai_agent_welcome_analytics: "Here you can see platform data. Ask me to explain a chart or what a certain metric means.",
    ai_agent_welcome_user_management: "From here you can manage all users. I can assist with understanding different roles and permissions.",
    ai_agent_welcome_settings: "In Settings, you can manage your profile. Ask me how to update your Skill Passport or change your language.",
    ai_agent_welcome_leave_management: "In Leave Management, you can request time off or manage team requests. Ask me how to submit a request.",
    my_time_logs: "My Time Logs",
    time_tracking_subtitle: "View, manage, and schedule your time across all activities.",
    total_time_logged: "Total Time Logged",
    duration_minutes: "Duration (minutes)",
    log_entry_for: "Log entry for",
    no_time_logs_found: "No time logs found.",
    time_logged_today: "Time Logged Today",
    time_logged_this_week: "Time Logged This Week",
    new_log_entry: "New Time Log Entry",
    select_type: "Select type...",
    select_course: "Select a Course",
    select_task_optional: "Select a Task (optional)",
    description: "Description",
    minutes: "minutes",
    view_time_logs: "View Time Logs",
    leave_management: "Leave Request",
    leave_management_subtitle: "Request and manage your time off requests.",
    manage_leaves: "Manage Leaves",
    request_leave: "Request Leave",
    my_requests: "My Requests",
    team_requests: "Team Requests",
    start_date: "Start Date",
    end_date: "End Date",
    reason: "Reason",
    submit_request: "Submit Request",
    approve: "Approve",
    reject: "Reject",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    no_leave_requests: "No leave requests found.",
    team_availability: "Team Availability",
    upcoming_leaves: "Upcoming Leaves (Next 7 days)",
    no_upcoming_leaves: "No upcoming leaves.",
    signup_title: "Create Your Account",
    signup_subtitle: "Join the future of productivity.",
    full_name: "Full Name",
    phone_number: "Phone Number",
    password: "Password",
    confirm_password: "Confirm Password",
    signup_button: "Sign Up",
    signup_prompt: "Don't have an account? Sign up",
    login_prompt: "Already have an account? Login",
    login_highlight_roles_title: "Roles & Access",
    login_highlight_roles_description: "Advanced roles may require an invitation",
    login_error_generic: "An error occurred during login. Please try again.",
    login_error_invalid_credentials: "Invalid credentials or account not found. Check your email/password or create a new account.",
    login_error_account_not_found: "This account does not exist or has been removed. Verify the email address or create a new account.",
    login_error_wrong_password: "Incorrect password. Try again or click “Forgot password?”.",
    login_error_email_not_confirmed: "Your email must be confirmed before logging in. Check your inbox.",
    login_email_in_use_error: "This email is already in use. Use another email or sign in.",
    login_unexpected_error: "Unexpected error while signing in.",
    login_loading: "Signing in...",
    login_organization_loading: "Loading organizations…",
    login_organization_hint: "Choose your organization. If it doesn't exist, it will be created automatically after login (if allowed).",
    login_organization_info_title: "Information",
    login_organization_info_line1: "Platform brand. SENEGEL remains the reference organization for public testing.",
    login_partner_org_label: "Partner organizations",
    login_organization_info_line2: "Access by invitation only, created by Super Admins.",
    login_reset_success: "A reset link has been sent to your email.",
    login_reset_error: "Error while sending the reset link.",
    login_reset_title: "Reset your password",
    login_reset_cancel: "Cancel",
    login_reset_send: "Send link",
    login_reset_sending: "Sending...",
    signup_hero_tagline: "Creating Opportunities for Youth in Africa",
    signup_hero_subtagline: "Intelligent multi-organization platform",
    signup_highlight_multi_org_title: "Multi-Organizations",
    signup_highlight_multi_org_description: "Each organization has its own secure space",
    signup_highlight_unified_title: "Unified Ecosystem",
    signup_highlight_unified_description: "One platform, many organizations, thousands of users",
    signup_highlight_security_title: "Security & Isolation",
    signup_highlight_security_description: "Your data stays isolated inside your organization",
    signup_role_group_management: "Management",
    signup_role_group_pedagogy: "Pedagogy & Facilitation",
    signup_role_group_youth: "Youth & Academic",
    signup_role_group_entrepreneurship: "Entrepreneurship & Partnerships",
    signup_role_group_creative: "Creative & Media",
    signup_role_group_partners: "Partner Facilitators",
    signup_role_group_super_admin: "Super Administration",
    signup_organization_label: "Organization",
    signup_organization_placeholder: "e.g., SENEGEL or Partner ABC",
    signup_organization_hint: "SENEGEL by default. If the partner organization does not exist yet, it will be created automatically.",
    signup_banner_title: "Account Creation",
    signup_banner_description_prefix: "You are creating an account in",
    signup_banner_description_suffix: "Choose any available role according to your responsibilities.",
    signup_banner_all_roles_label: "All roles available",
    signup_banner_all_roles_description: "Pick any role from the MVP (administrator, manager, supervisor, trainer, student, entrepreneur, etc.).",
    signup_banner_note_label: "Note",
    signup_banner_note_description: "The role super_administrator is reserved and can only be created by an existing Super Administrator.",
    signup_full_name_placeholder: "Your full name",
    signup_email_placeholder: "john.doe@email.com",
    signup_email_domain_warning: "⚠️ Some domains may be blocked. Use a valid email (Gmail, Outlook, etc.)",
    signup_phone_placeholder: "+221 XX XXX XX XX",
    signup_hide_password: "Hide password",
    signup_show_password: "Show password",
    signup_hide_confirm_password: "Hide confirm password",
    signup_show_confirm_password: "Show confirm password",
    signup_loading: "Creating account...",
    signup_role_requires_validation_message: "This role requires approval from a Super Administrator. Your account will remain pending until it is approved.",
    signup_all_roles_card_title: "All roles available",
    signup_all_roles_card_description: "Create an account with any role based on your needs. Each role comes with its own permissions and access.",
    signup_roles_management_label: "Management roles:",
    signup_roles_pedagogy_label: "Pedagogy & facilitation:",
    signup_roles_youth_label: "Youth & academic:",
    signup_roles_entrepreneurship_label: "Entrepreneurship & partnerships:",
    signup_roles_creative_label: "Creative & media:",
    signup_roles_partner_label: "Partner facilitators:",
    signup_roles_super_admin_label: "Super administration:",
    signup_roles_note_text: "Note: Advanced management roles (administrator, manager, supervisor, trainer, coach, facilitator, mentor, partner_facilitator and super_administrator) require approval from a Super Administrator.",
    signup_role_status_validation: "Approval required",
    signup_role_status_allowed: "Registration allowed",
    signup_role_status_validation_message: "Your request for the {role} role will be reviewed by a Super Administrator before activation.",
    signup_role_status_allowed_message: "You can create an account with the {role} role. Permissions are applied immediately after signup.",
    signup_error_generic: "An error occurred during signup. Please try again.",
    signup_error_email_exists: "This email is already registered. Please sign in or use another email.",
    signup_error_invalid_email: "Invalid email address. Please check the format or use another domain.",
    signup_error_password_short: "Password is too short. Use at least 8 characters mixing letters and numbers.",
    signup_password_min_length: "Password must contain at least 8 characters.",
    signup_role_unavailable: 'The "{role}" role is no longer available. Another account already uses it.',
    signup_email_in_use_detailed: "This email is already in use. Use another email or sign in.",
    signup_invalid_email_hint: "Invalid email. Please use a valid email (e.g., yourname@gmail.com).",
    passwords_do_not_match: "Passwords do not match.",
    email_in_use: "This email is already in use.",
    login_title: "Welcome Back!",
    login_subtitle: "Empowering your workflow, securely.",
    forgot_password: "Forgot Password?",
    need_help: "Need Help?",
    auth_ai_assistant_title: "Auth AI Assistant",
    password_strength: "Password Strength",
    strength_weak: "Weak",
    strength_medium: "Medium",
    strength_strong: "Strong",
    strength_very_strong: "Very Strong",
    auth_ai_prompt_roles: "What's the difference between the roles?",
    auth_ai_prompt_password: "I forgot my password. What do I do?",
    estimated_time_short: "Est. (h)",
    logged_time_short: "Logged (h)",
    finance: "Finance",
    finance_title: "Streamline Financial Operations & Optimize Profitability",
    finance_subtitle: "Rigorous financial management is the foundation of stability and growth. The Finance module centralizes all your financial operations, simplifying cash flow management and expense tracking.",
    finance_partial_payment_amount_required: "Please enter a valid paid amount for a partial payment.",
    finance_partial_payment_must_be_less_total: "The paid amount must be lower than the total. Set the status to “Paid” if the invoice is fully paid.",
    finance_partial_payment_cannot_exceed_total: "The paid amount cannot exceed the total amount of the invoice.",
    finance_paid_amount_placeholder: "e.g., 1500",
    finance_total_amount_label: "Total amount",
    finance_amount_remaining_label: "Amount remaining",
    view_finance: "View Finance",
    invoices: "Invoices",
    expenses: "Expenses",
    recurring: "Recurring",
    budgets: "Budgets",
    new_invoice: "New Invoice",
    new_expense: "New Expense",
    new_budget: "New Budget",
    total_revenue: "Total Revenue",
    total_expenses: "Total Expenses",
    net_income: "Net Income",
    total_outstanding_invoices: "Outstanding Invoices",
    total_due_expenses: "Due Expenses",
    average_payment_time: "Avg. Payment Time",
    days: "days",
    overdue: "Overdue",
    invoice_number: "Invoice #",
    client_name: "Client Name",
    amount: "Amount",
    draft: "Draft",
    sent: "Sent",
    paid: "Paid",
    partially_paid: "Partially Paid",
    paid_amount: "Paid Amount",
    unpaid: "Unpaid",
    category: "Category",
    date: "Date",
    create_invoice: "Create Invoice",
    edit_invoice: "Edit Invoice",
    create_expense: "Create Expense",
    edit_expense: "Edit Expense",
    delete_invoice: "Delete Invoice",
    delete_expense: "Delete Expense",
    receipt: "Receipt",
    upload_receipt: "Upload Receipt",
    download_receipt: "Download Receipt",
    view_receipt: "View Receipt",
    no_receipt_attached: "No receipt",
    payable_by: "Payable By",
    remove_receipt: "Remove",
    evidence_documents: "Evidence Documents",
    upload_evidence: "Upload Evidence",
    download_evidence: "Download Evidence",
    no_evidence_uploaded: "No evidence uploaded yet.",
    remove_evidence: "Remove",
    notifications: "Notifications",
    no_notifications: "No new notifications",
    reminder_settings: "Reminder Settings",
    remind_days_before: "Remind me (days before due)",
    invoice_due_reminder: "Invoice {invoiceNumber} is due on {dueDate}.",
    expense_due_reminder: "Expense for '{description}' is payable on {dueDate}.",
    mark_as_read: "Mark as read",
    clear_all: "Clear All",
    make_recurring: "Make this recurring?",
    frequency: "Frequency",
    monthly: "Monthly",
    quarterly: "Quarterly",
    annually: "Annually",
    end_date_optional: "End Date (Optional)",
    recurring_invoices: "Recurring Invoices",
    recurring_expenses: "Recurring Expenses",
    next_due_date: "Next Due Date",
    new_recurring_invoice: "New Recurring Invoice",
    new_recurring_expense: "New Recurring Expense",
    finance_invoice_found_singular: "invoice found",
    finance_invoice_found_plural: "invoices found",
    finance_expense_found_singular: "expense found",
    finance_expense_found_plural: "expenses found",
    finance_no_invoice_match: "No invoice matches the filters",
    finance_no_invoice: "No invoice",
    finance_no_expense_match: "No expense matches the filters",
    finance_no_expense: "No expense",
    finance_partial_payment_constraint_error: "❌ ERROR: Unable to create an invoice with status “Partially Paid”.\n\n🔧 REQUIRED ACTION (2 minutes):\n1. Go to https://supabase.com/dashboard\n2. Open “SQL Editor” → “New query”\n3. Paste the script from docs/ACTIVER-PAIEMENT-PARTIEL.md\n4. Click “Run”\n5. Reload this page and try again.",
    finance_save_invoice_error: "Error while saving the invoice. Please try again.",
    finance_currency_field_label: "Currency",
    finance_transaction_date: "Transaction Date",
    finance_use_manual_rate: "Use manual exchange rate",
    finance_manual_exchange_rate: "Exchange rate to USD",
    finance_manual_rate_help: "Leave empty to use automatic API rate",
    goal_title_required: "Objective title is required.",
    goal_key_result_title_required: "Each Key Result must have a title.",
    goal_key_result_target_positive: "A Key Result target must be greater than 0.",
    goal_key_result_current_range: "The current value must be between 0 and the target.",
    goal_select_project: "Select a project",
    goal_missing_id_error: "Error: unable to update the objective because the ID is missing.",
    goal_generate_error: "Error while generating OKRs. Please try again.",
    project_permission_error: "You are not allowed to edit or delete this project.",
    project_title_required: "Project title is required.",
    project_description_required: "Project description is required.",
    project_due_date_invalid: "Due date cannot be in the past.",
    project_missing_id_error: "Error: unable to update the project because the ID is missing.",
    create_budget: "Create Budget",
    edit_budget: "Edit Budget",
    delete_budget: "Delete Budget",
    budget_title: "Budget Title",
    budget_type: "Budget Type",
    project_budget: "Project Budget",
    office_management: "Office Management",
    total_budget: "Total Budget",
    amount_spent: "Amount Spent",
    remaining: "Remaining",
    link_to_budget: "Link to Budget (Optional)",
    link_to_budget_help: "Link this expense to a budget item to track spending against planned budget.",
    optional: "Optional",
    no_budget: "No Budget",
    view_details: "View Details",
    view_entity: "View Entity",
    action_details: "Action Details",
    summary: "Summary",
    changes: "Changes",
    before: "Before",
    after: "After",
    other_metadata: "Other Metadata",
    no_history: "No activity recorded.",
    loading: "Loading...",
    load_more: "Load More",
    system: "System",
    yes: "Yes",
    no: "No",
    activity_history: "Activity History",
    activity_history_subtitle: "Complete tracking of actions performed on the platform.",
    all_modules: "All Modules",
    all_actions: "All Actions",
    budget_lines: "Budget Lines",
    add_budget_line: "Add Budget Line",
    add_budget_item: "Add Item",
    item_description: "Item Description",
    planned_amount: "Planned",
    actual_spent: "Actual",
    calendar_and_meetings: "Calendar & Meetings",
    schedule_meeting: "Schedule Meeting",
    new_meeting: "New Meeting",
    edit_meeting: "Edit Meeting",
    delete_meeting: "Delete Meeting",
    meeting_title: "Meeting Title",
    start_time: "Start Time",
    end_time: "End Time",
    attendees: "Attendees",
    meeting_details: "Meeting Details",
    log_time_for_meeting: "Log Time for this Meeting",
    no_meetings_today: "No meetings scheduled for this day.",
    today: "Today",
    previous_week: "Previous Week",
    next_week: "Next Week",
    image_editing: "Image Editing",
    upload_image_to_edit: "Upload an image to get started",
    editing_prompt_placeholder: "e.g., Make this photo look like a watercolor painting",
    generate_edit: "Generate Edit",
    original_image: "Original Image",
    edited_image: "Edited Image",
    remove_image: "Remove Image",
    download_image: "Download Image",
    project_saved: "Project saved successfully.",
    invoice_saved: "Invoice saved successfully.",
    expense_saved: "Expense saved successfully.",
    contact_saved: "Contact saved successfully.",
    item_deleted: "Item deleted.",
    project_status_overview: "Project Status Overview",
    proactive_ai_suggestion_tasks: "Need help brainstorming tasks for your new project?",
    proactive_ai_suggestion_overdue: "I can help draft a reminder for your overdue invoices.",
    status_selector_title: "Choose your status",
    status_selector_subtitle: "This status will be recorded and can be changed from the dashboard. Time is counted only when you are not absent.",
    status_selector_skip_next: "Do not ask on every login",
    status_selector_confirm: "Enter the platform",
    status_present: "Present / Online",
    status_absent: "Absent",
    status_pause_coffee: "Coffee break",
    status_pause_lunch: "Lunch break",
    status_in_meeting: "In a meeting",
    status_away_mission: "Away / External mission",
    status_brief_team: "Team brief",
    status_technical_issue: "Technical issue",
    status_timer_today: "Today",
    status_not_counted: "Time not counted (absent)",
    status_selector_modal_message: "Please choose the appropriate status to continue. You can change it anytime from the dashboard.",
    status_selector_help: "Help",
    status_selector_help_title: "Status guide",
    status_help_intro: "Select the status that best matches your current activity. Time is only counted when you are not absent.",
    status_help_present: "You are at work and available.",
    status_help_absent: "You are not working; time is not counted.",
    status_help_pause_coffee: "Short break (e.g. coffee).",
    status_help_pause_lunch: "Lunch break.",
    status_help_in_meeting: "In a meeting or call.",
    status_help_away_mission: "Away from office (external mission, travel).",
    status_help_brief_team: "Team briefing or stand-up.",
    status_help_technical_issue: "Technical issue (IT, connection, etc.).",
    current_status: "Current status",
    change_status: "Change",
    no_presence_session: "No session in progress",
    profile_photo_upload: "Change profile photo",
    profile_photo_uploaded: "Photo updated.",
    demo_next: "Next",
    demo_prev: "Back",
    demo_auto: "Auto demo",
    demo_pause: "Pause",
    demo_close: "Close",
    demo_step_intro: "Your status determines whether your time is counted. Choose the one that matches your activity.",
    demo_step_of: "of",
  },
  [Language.FR]: {
    loginAs: "Se connecter en tant que",
    // User Roles
    student: "Étudiant",
    learner: "Apprenant",
    entrepreneur: "Entrepreneur",
    employer: "Employeur",
    trainer: "Formateur",
    funder: "Bailleur de fonds",
    implementer: "Implémenteur",
    mentor: "Mentor",
    coach: "Coach",
    facilitator: "Facilitateur",
    partner_facilitator: "Facilitateur partenaire",
    publisher: "Éditeur",
    editor: "Rédacteur",
    producer: "Producteur",
    artist: "Artiste",
    hr_business_partner: "Chargé·e RH / partenaire métier",
    hr_officer: "Assistant·e RH",
    recruiter: "Recruteur·se",
    payroll_specialist: "Spécialiste paie",
    team_lead: "Chef·fe d’équipe",
    alumni: "Ancien élève",
    intern: "Stagiaire",
    supervisor: "Superviseur",
    manager: "Manager",
    administrator: "Administrateur",
    super_administrator: "Super Administrateur",
    // Role Categories
    youth: "Jeunesse",
    entrepreneur_category: "Entrepreneuriat & Partenariats",
    contributor_category: "Contributeur",
    staff_category: "Personnel",
    hr_staff_category: "RH & pilotage d’équipe",
    super_admin_category: "Super Administrateur",

    login: "Connexion",
    dashboard: "Tableau de Bord",
    courses: "Formations",
    jobs: "Emplois",
    settings: "Paramètres",
    logout: "Déconnexion",
    welcome: "Bienvenue",
    dashboard_title: "Votre Tableau de Bord",
    dashboard_subtitle: "Voici un aperçu de votre activité.",
    dashboard_week: "Semaine",
    dashboard_month: "Mois",
    dashboard_no_data_period: "Aucune donnée sur la période",
    dashboard_hours: "Heures",
    no_recent_activity: "Aucune activité récente",
    view_all: "Voir tout",
    my_courses: "Mes Formations",
    view_all_courses: "Voir Toutes les Formations",
    job_openings: "Offres d'Emploi",
    view_all_jobs: "Voir Tous les Emplois",
    settings_title: "Paramètres",
    language: "Langue",
    english: "Anglais",
    french: "Français",
    profile: "Profil",
    senegel_workflow_platform: "COYA",
    course_duration: "Durée",
    course_progress: "Progression",
    job_posted: "Publié le",
    job_type: "Type",
    job_location: "Lieu",
    projects: "Projets",
    project_management_title: "Gestion de Projets Intelligente",
    project_management_subtitle: "Créez, gérez et suivez vos projets avec l'assistance de l'IA.",
    new_project: "Nouveau Projet",
    create_project: "Créer le Projet",
    project_title: "Titre du Projet",
    project_description: "Description du Projet",
    due_date: "Date d'Échéance",
    team_members: "Membres de l'équipe",
    selected_team_members: "Membres sélectionnés",
    add_team_members: "Ajouter des membres",
    loading_users: "Chargement des utilisateurs",
    no_users_found: "Aucun utilisateur trouvé",
    no_users_available: "Aucun utilisateur disponible",
    delete_project: "Supprimer le projet",
    confirm_delete_project: "Êtes-vous sûr de vouloir supprimer ce projet ? Cette action ne peut pas être annulée.",
    status: "Statut",
    not_started: "Non commencé",
    in_progress: "En cours",
    completed: "Terminé",
    tasks: "Tâches",
    to_do: "À Faire",
    done: "Terminé",
    generate_tasks_with_ai: "Générer les Tâches avec l'IA",
    image_generator: "Générateur d'Images",
    image_generator_subtitle: "Créez des images époustouflantes à partir de descriptions textuelles. Propulsé par Imagen.",
    image_prompt_placeholder: "ex: Une scène de marché animée à Dakar avec des éléments futuristes",
    generate_image: "Générer l'Image",
    generating: "Génération...",
    my_skills: "Mes Compétences (Passeport de Compétences)",
    skill_passport_subtitle: "Cela nous aide à vous mettre en relation avec les bons emplois et projets.",
    add_skill: "Ajouter Compétence",
    enter_skill: "Entrez une compétence...",
    my_job_postings: "Mes Offres d'Emploi",
    applicants: "Candidats",
    no_applicants: "Aucun candidat pour le moment.",
    view_applicants: "Voir les Candidats",
    apply_now: "Postuler",
    applied: "Postulé",
    ai_smart_match: "Match Intelligent IA",
    top_candidate: "Meilleur Candidat",
    my_projects: "Mes Projets",
    view_all_projects: "Voir Tous les Projets",
    course_detail: "Détail de la Formation",
    back_to_courses: "Retour aux Formations",
    modules: "Modules",
    lessons: "Leçons",
    start_learning: "Commencer l'Apprentissage",
    continue_learning: "Continuer l'Apprentissage",
    course_management: "Gestion des Formations",
    course_management_subtitle: "Créez, modifiez et organisez toutes les formations de la plateforme.",
    add_new_course: "Ajouter une Formation",
    edit_course: "Modifier la Formation",
    analytics: "Analytique",
    platform_analytics: "Analytiques de la Plateforme",
    platform_analytics_subtitle: "Métriques clés et aperçus de l'activité de la plateforme.",
    user_growth: "Croissance des Utilisateurs",
    enrollment_trends: "Tendances d'Inscription",
    job_application_funnel: "Entonnoir de Candidature",
    view_talent_analytics: "Voir l'Analyse des Talents",
    talent_analytics: "Analyse des Talents",
    talent_analytics_subtitle: "Aperçu des compétences et du potentiel de notre base d'utilisateurs.",
    back_to_analytics: "Retour aux Analytiques",
    skill_gap_analysis: "Analyse des Écarts de Compétences",
    most_demanded_skills: "Compétences les Plus Demandées (des offres d'emploi)",
    available_skills: "Top Compétences Disponibles (des passeports utilisateurs)",
    talent_forecasting: "Prévision des Talents",
    talent_forecasting_subtitle: "Utilisez l'IA pour prédire les futurs besoins et la disponibilité des talents.",
    forecast_needs: "Prévoir les Besoins",
    goals_okrs: "Objectifs (OKRs)",
    risk_management: "Gestion des Risques",
    crm_sales: "CRM & Ventes",
    knowledge_base: "DOCS SENEGEL",
    goals_okrs_title: "Alignement des objectifs stratégiques (OKR)",
    goals_okrs_subtitle: "Définissez et suivez les objectifs et les résultats clés de vos projets.",
    select_project: "Sélectionnez un projet",
    generate_okrs_with_ai: "Générer des OKR avec l'IA",
    objective: "Objectif",
    key_results: "Principaux résultats",
    ai_okr_suggestions: "Suggestions OKR générées par l'IA",
    add_to_project: "Ajouter au projet",
    risk_management_tab: "Gestion des Risques",
    identify_risks_with_ai: "Identifier les Risques avec l'IA",
    likelihood: "Probabilité",
    impact: "Impact",
    mitigation_strategy: "Stratégie d'Atténuation",
    high: "Élevé",
    medium: "Moyen",
    low: "Faible",
    priority: "Priorité",
    assignee: "Assigné à",
    unassigned: "Non assigné",
    time_tracking: "Suivi du Temps",
    log_time: "Pointer",
    generate_status_report: "Générer un Rapport d'Avancement",
    summarize_tasks: "Résumer les Tâches",
    crm_title: "Gestion de la Relation Client",
    crm_subtitle: "Gérez vos contacts et votre pipeline de ventes.",
    crm_kpi_total_contacts: "Contacts totaux",
    crm_kpi_leads: "Pistes",
    crm_kpi_prospects: "Prospects",
    crm_kpi_customers: "Clients",
    crm_kpi_conversion: "Conversion",
    draft_email_with_ai: "Rédiger un E-mail avec l'IA",
    crm_permission_denied: "Vous n’avez pas les droits pour cette action sur ce contact.",
    crm_default_sales_context: "Présenter nos services et proposer un court échange de découverte.",
    crm_draft_email_title: "Brouillon d’e-mail",
    crm_draft_ai_error: "La génération IA a échoué. Utilisez le modèle ci-dessous ou rédigez votre message.",
    crm_draft_fallback_body: "Bonjour,\n\nNous serions heureux d’échanger sur la manière dont nous pouvons accompagner votre structure.\n\nCordialement",
    crm_email_copy: "Copier le texte",
    crm_email_open_mail: "Ouvrir la messagerie",
    crm_email_close: "Fermer",
    crm_email_copy_ok: "Copié dans le presse-papiers",
    crm_email_copy_fail: "La copie a échoué",
    crm_persist_failed: "Le contact n’a pas pu être enregistré sur le serveur ; la collecte n’a pas été marquée comme liée.",
    crm_filter_campaign_origin: "Origine campagne",
    crm_filter_all_campaigns: "Toutes les campagnes",
    crm_column_collecte: "Collecte",
    crm_badge_collecte: "Collecte",
    crm_import_submissions: "Importer les soumissions",
    crm_collecte_enrich_modal_title: "Lier une collecte au CRM",
    crm_collecte_enrich_modal_body:
      "Privilégiez la synchronisation des vraies soumissions (lot) depuis le module Collecte : chaque contact portera les identifiants campagne et soumission. Vous pouvez encore créer un contact « repère » avec e-mail fictif.",
    crm_collecte_placeholder_note: "Secondaire : contact repère (e-mail fictif)",
    crm_open_collecte: "Ouvrir l’atelier Collecte (dans ce CRM)",
    crm_search_contacts_placeholder: "Rechercher par nom, entreprise ou e-mail…",
    crm_hide_placeholder_emails: "Masquer les e-mails fictifs de collecte",
    collecte_submissions_synced_ratio: "Synchronisés CRM",
    collecte_open_in_crm: "Ouvrir dans le CRM (filtré)",
    crm_enrich_from_collecte: "Enrichir depuis une collecte",
    crm_tab_collecte: "Collecte & imports",
    crm_collecte_hub_title: "La collecte dans le CRM",
    crm_collecte_hub_subtitle:
      "Pilotez les campagnes locales, les soumissions, la synchronisation et les contacts CRM issus de la Collecte — sans quitter ce module.",
    crm_collecte_sync_all_pending: "Synchroniser toutes les soumissions en attente",
    crm_collecte_sync_result: "Synchronisation terminée",
    crm_collecte_sync_skipped: "ignorées ou en échec",
    crm_collecte_kpi_submissions: "Soumissions",
    crm_collecte_kpi_pending: "En attente sync",
    crm_collecte_kpi_synced_local: "Synchronisées (local)",
    crm_collecte_kpi_crm_from_collecte: "Contacts CRM (Collecte)",
    crm_collecte_campaigns_title: "Campagnes",
    crm_collecte_empty_campaigns:
      "Aucune campagne locale pour cette organisation. Utilisez l’onglet « Collecte & imports » de ce CRM pour en créer une.",
    crm_collecte_badge_linked: "Lien CRM marqué",
    crm_collecte_row_submissions: "Soumissions",
    crm_collecte_row_pending: "En attente",
    crm_collecte_row_crm: "Dans le CRM",
    crm_collecte_action_filter_crm: "Filtrer les contacts",
    crm_collecte_action_open_collecte: "Préremplir dans l’onglet Collecte (ce CRM)",
    crm_collecte_action_sync_campaign: "Synchroniser cette campagne",
    crm_webhook_card_title: "Webhooks HTTP signés (relai serveur)",
    crm_webhook_card_body:
      "Les événements (contact créé/mis à jour, sync Collecte) sont envoyés en POST par une Edge Function Supabase avec l’en-tête X-Coya-Signature: sha256=<hmac>. Indiquez des URL en HTTPS ; le secret de signature n’est affiché qu’une fois à la création ou après régénération.",
    crm_webhook_no_org: "Aucune organisation n’est liée à votre profil — configuration des webhooks impossible.",
    crm_webhook_error_https: "L’URL doit commencer par https://",
    crm_webhook_confirm_delete: "Supprimer ce point de terminaison webhook ?",
    crm_webhook_confirm_regenerate:
      "Régénérer le secret de signature ? L’ancien secret cessera de fonctionner immédiatement.",
    crm_webhook_secret_once: "Copiez ce secret maintenant : il ne sera plus affiché dans la liste.",
    crm_webhook_secret_dismiss: "Masquer",
    crm_webhook_add_title: "Nouveau point de terminaison",
    crm_webhook_url_placeholder: "https://exemple.com/hooks/coya",
    crm_webhook_label_placeholder: "Libellé (optionnel, ex. n8n prod)",
    crm_webhook_add_button: "Ajouter le webhook",
    crm_webhook_list_title: "Points configurés",
    crm_webhook_refresh: "Actualiser",
    crm_webhook_empty: "Aucun webhook. Ajoutez une URL HTTPS pour recevoir les charges CRM signées.",
    crm_webhook_last: "Dernière livraison",
    crm_webhook_never: "Jamais livré",
    crm_webhook_disable: "Désactiver",
    crm_webhook_enable: "Activer",
    crm_webhook_regenerate: "Nouveau secret",
    crm_webhook_delete: "Supprimer",
    crm_webhook_ping: "Tester la livraison",
    crm_webhook_ping_ok: "Relai invoqué (vérifiez la cible et le statut de dernière livraison).",
    crm_webhook_ping_fail: "Échec du test",
    crm_webhook_readonly: "Seuls les gestionnaires et administrateurs peuvent modifier les webhooks.",
    crm_collecte_enrich_modal_empty_hint:
      "Aucune campagne éligible. Créez-en dans l’onglet « Collecte & imports » du CRM (atelier ci-dessous), puis revenez ici.",
    crm_dossier_badge: "Dossier client",
    crm_dossier_col: "Dossier",
    crm_dossier_open: "Ouvrir le dossier (historique, notes, liens)",
    crm_dossier_open_short: "Dossier",
    crm_dossier_tab_timeline: "Historique",
    crm_dossier_tab_notes: "Notes",
    crm_dossier_tab_files: "Liens & pièces",
    crm_dossier_empty_timeline: "Aucune entrée pour l’instant. Les modifications du contact sont journalisées à l’enregistrement.",
    crm_dossier_empty_notes: "Aucune note.",
    crm_dossier_empty_files: "Aucun lien ni pièce référencée.",
    crm_dossier_add_note: "Ajouter une note",
    crm_dossier_note_title_ph: "Titre",
    crm_dossier_note_body_ph: "Détail (optionnel)",
    crm_dossier_save_note: "Enregistrer la note",
    crm_dossier_add_link: "Ajouter un lien externe",
    crm_dossier_link_title_ph: "Libellé du lien",
    crm_dossier_save_link: "Enregistrer le lien",
    crm_dossier_add_file_ref: "Fichier / contrat (URL ou lien stockage)",
    crm_dossier_file_label_ph: "Nom du document",
    crm_dossier_file_url_ph: "https://… ou chemin de stockage",
    crm_dossier_save_file_ref: "Enregistrer la référence",
    crm_dossier_confirm_delete: "Supprimer cette entrée du dossier ?",
    crm_contact_detail_back: "Retour à la liste",
    crm_contact_detail_title: "Fiche contact",
    crm_contact_detail_edit: "Modifier",
    crm_contact_detail_delete: "Supprimer",
    crm_contact_detail_draft_email: "Brouillon e-mail IA",
    crm_contact_detail_section_crm: "Informations CRM",
    crm_contact_detail_section_collecte: "Collecte (soumission)",
    crm_contact_detail_collecte_submitted_at: "Soumis le :",
    crm_contact_detail_collecte_no_local:
      "Aucune soumission locale n’est liée à ce contact (stockage navigateur). Les champs CRM ci-dessus restent ceux synchronisés ; ouvrez l’onglet Collecte pour gérer les campagnes.",
    crm_contact_detail_collecte_empty_payload: "Soumission présente mais payload vide.",
    crm_contact_detail_go_collecte: "Ouvrir la campagne dans l’onglet Collecte",
    crm_contact_detail_source: "Origine",
    crm_contact_detail_created_by: "Créé par",
    crm_contact_detail_notes: "Notes",
    crm_contact_detail_tags: "Étiquettes",
    crm_contact_detail_not_found: "Ce contact n’est plus dans la liste.",
    crm_integrations_title: "Intégrations & applications partenaires",
    crm_integrations_body:
      "Les événements sortants sont diffusés vers les écouteurs enregistrés et vers window.__COYA_CRM_EVENT__ pour d'autres applis web (iframe, extension navigateur, ou proxy). Sert à refléter contacts, synchronisations et automatisations dans un autre SI.",
    knowledge_base_title: "DOCS SENEGEL",
    knowledge_base_subtitle: "Bibliothèque documentaire : dossiers avec contrôle d'accès (propriétaire + invités lecteur/éditeur), fichiers Office et PDF.",
    daf_services: "Moyens généraux & DAF",
    daf_services_title: "Demandes moyens généraux & DAF",
    daf_services_subtitle: "Transmettre des demandes internes (fournitures, logistique, IT, véhicule, etc.) à la direction administrative et financière.",
    daf_new_request: "Nouvelle demande",
    daf_my_requests: "Mes demandes",
    daf_category: "Catégorie",
    daf_status: "Statut",
    daf_title_field: "Titre",
    daf_description: "Description",
    daf_submit: "Envoyer",
    daf_save_draft: "Enregistrer brouillon",
    daf_daf_comment: "Commentaire DAF",
    daf_intro_workflows:
      "Choisissez un circuit : demande générale, remise de documents officiels, réponse d'information (texte, lien ou fichier), ou cycle de signature (dépôt, envoi pour signature, retour signé).",
    daf_request_kind: "Type de demande",
    daf_request_kind_help:
      "Remise de documents : la DAF joint les fichiers à transmettre. Information : la DAF répond par message, lien et/ou pièce jointe. Signature : joindre le document à faire signer, suivre l'envoi externe puis le retour signé.",
    daf_queue_org: "File organisation (DAF / managers)",
    daf_empty_list: "Aucune demande pour l'instant.",
    daf_open_detail: "Ouvrir",
    daf_close_detail: "Fermer",
    daf_status_draft: "Brouillon",
    daf_status_submitted: "Envoyée",
    daf_status_in_review: "En traitement",
    daf_status_awaiting_requester: "En attente du demandeur",
    daf_status_pending_external_signature: "En signature externe",
    daf_status_approved: "Approuvée",
    daf_status_rejected: "Refusée",
    daf_status_fulfilled: "Clôturée",
    daf_status_cancelled: "Annulée",
    daf_kind_general: "Générale",
    daf_kind_document_delivery: "Remise de documents",
    daf_kind_information: "Information / réponse",
    daf_kind_signature_workflow: "Circuit signature",
    daf_wf_hint_general: "Traitement classique : prise en charge, approbation, refus ou clôture.",
    daf_wf_hint_document: "La DAF joint les documents officiels puis clôt lorsque la remise est faite.",
    daf_wf_hint_information: "La DAF publie une réponse (message, lien, fichier optionnel). Clôturer lorsque le demandeur a reçu l'information.",
    daf_wf_hint_signature: "Joindre le fichier à signer, indiquer l'envoi pour signature, puis joindre le retour signé et clôturer.",
    daf_signature_phase: "Phase signature",
    daf_phase_none: "Non démarrée",
    daf_phase_original_provided: "Original fourni",
    daf_phase_sent_for_signature: "Envoyé pour signature",
    daf_phase_signed_returned: "Retour signé reçu",
    daf_thread_title: "Échanges",
    daf_thread_empty: "Aucun message pour l'instant.",
    daf_add_message: "Ajouter un message",
    daf_message_placeholder: "Votre message…",
    daf_link_placeholder: "Lien optionnel (URL)",
    daf_internal_only: "Note interne (DAF / managers uniquement)",
    daf_post_message: "Publier",
    daf_you: "Vous",
    daf_participant: "Participant",
    daf_internal_note: "interne",
    daf_attachments_title: "Pièces jointes",
    daf_attachments_empty: "Aucune pièce jointe.",
    daf_download: "Télécharger",
    daf_attach_supporting: "Pièce justificative",
    daf_attach_signature_original: "Document à signer",
    daf_attach_daf_deliverable: "Document remis",
    daf_attach_info_answer: "Fichier réponse (info)",
    daf_attach_signature_signed: "Retour signé",
    daf_reviewer_actions: "Actions DAF / manager",
    daf_action_take_in_review: "Prendre en charge",
    daf_action_take_ownership: "M’assigner la demande",
    daf_assign_unassigned: "Non assignée",
    daf_assign_me: "Assignée à moi",
    daf_assign_other: "Assignée",
    daf_action_await_requester: "Demander des précisions au demandeur",
    daf_optional_comment: "Commentaire pour le demandeur (optionnel)",
    daf_upload_deliverable: "Téléversez le(s) document(s) à remettre au demandeur.",
    daf_choose_file: "Choisir un fichier",
    daf_action_close_document: "Marquer comme remis / clôturer",
    daf_info_upload_hint: "Optionnel : joindre un fichier avec l'information (en plus du message ou du lien).",
    daf_attach_info_file: "Joindre fichier de réponse",
    daf_action_close_information: "Clôturer (information fournie)",
    daf_signature_reviewer_hint:
      "Lorsque le document est chez le signataire, marquez l'envoi. Lorsque le PDF signé revient, téléversez-le ici.",
    daf_action_mark_sent_sign: "Marquer « envoyé pour signature »",
    daf_upload_signed_return: "Téléverser le retour signé",
    daf_action_close_after_signature: "Clôturer après retour signé",
    daf_action_signed_received: "Retour signé reçu — poursuivre le traitement",
    daf_action_approve: "Approuver",
    daf_action_reject: "Refuser",
    daf_action_fulfill: "Clôturer / traitée",
    daf_requester_reply_hint: "La DAF attend votre complément.",
    daf_requester_upload_support: "Vous pouvez joindre des fichiers puis confirmer que vous avez répondu.",
    daf_action_requester_done: "J'ai fourni les éléments demandés",
    daf_requester_files: "Vos pièces jointes",
    drive_my_drive: "Parcourir",
    drive_acl_title: "Accès au dossier",
    drive_acl_add: "Inviter",
    drive_acl_remove: "Retirer",
    drive_acl_permission_viewer: "Lecteur",
    drive_acl_permission_editor: "Éditeur",
    drive_acl_owner: "Propriétaire",
    drive_acl_help: "Seuls le propriétaire et les personnes invitées voient ce dossier et ses fichiers. Les administrateurs ont toujours accès.",
    drive_office_only_hint: "Types autorisés : PDF, Word, Excel, PowerPoint et équivalents.",
    drive_folder_visibility: "Visibilité du dossier",
    drive_folder_visibility_help: "Privé = uniquement les invités. Public = visible par toute l'organisation.",
    drive_visibility_private: "Privé (invités uniquement)",
    drive_visibility_org_public: "Public (organisation)",
    drive_visibility_no_rights: "Vous n'avez pas le droit de changer la visibilité.",
    drive_copy: "Copier",
    drive_cut: "Couper",
    drive_paste: "Coller",
    drive_view_grid: "Grille",
    drive_view_list: "Liste",
    drive_sort: "Tri",
    drive_sort_name_asc: "Nom (A→Z)",
    drive_sort_name_desc: "Nom (Z→A)",
    drive_sort_updated_desc: "Modifié (récent)",
    drive_sort_updated_asc: "Modifié (ancien)",
    drive_sort_created_desc: "Créé (récent)",
    drive_sort_created_asc: "Créé (ancien)",
    drive_items: "Éléments",
    drive_empty: "Aucun élément.",
    create_doc_from_text: "Créer un Document à Partir d'un Texte",
    paste_text_here: "Collez votre texte ici (ex: notes de réunion)...",
    summarize_and_create: "Résumer & Créer",
    all_documents: "Tous les Documents",
    create_new_job: "Créer une Offre d'Emploi",
    post_job: "Publier l'Offre",
    company_name: "Nom de l'Entreprise",
    job_title: "Titre du Poste",
    required_skills: "Compétences Requises",
    required_skills_placeholder: "ex: React, Node.js, Marketing (séparées par des virgules)",
    full_time: "Temps plein",
    part_time: "Temps partiel",
    contract: "Contrat",
    back_to_jobs: "Retour aux Emplois",
    user_management: "Gestion des Utilisateurs",
    user_management_subtitle: "Voir et gérer tous les utilisateurs de la plateforme.",
    name: "Nom",
    email: "E-mail",
    role: "Rôle",
    actions: "Actions",
    edit: "Modifier",
    delete: "Supprimer",
    search: "Rechercher",
    sort_by_date: "Trier par Date",
    sort_by_title: "Trier par Titre",
    sort_by_status: "Trier par Statut",
    sort_by_progress: "Trier par Progression",
    sort_by_duration: "Trier par Durée",
    sort_by_entity: "Trier par Entité",
    results_found: "résultats trouvés",
    total_logs: "Total Logs",
    total_hours: "Total Heures",
    daily_average: "Moyenne Quotidienne",
    all_types: "Tous les Types",
    delete_log: "Supprimer le Log",
    confirm_delete_log_message: "Êtes-vous sûr de vouloir supprimer ce log de temps ?",
    entity: "Entité",
    deactivate: "Désactiver",
    no_projects_found: "Aucun projet trouvé. Créez-en un pour commencer !",
    no_courses_found: "Aucune formation n'est disponible pour le moment. Veuillez revenir plus tard.",
    no_jobs_found: "Aucune offre d'emploi trouvée. Revenez plus tard ou créez-en une nouvelle !",
    save: "Enregistrer",
    cancel: "Annuler",
    confirm_delete: "Confirmer la Suppression",
    are_you_sure: "Êtes-vous sûr(e) ?",
    confirm_delete_message: "Cette action est irréversible. Toutes les données associées seront perdues.",
    edit_project: "Modifier le Projet",
    create_new_project: "Créer un Nouveau Projet",
    instructor: "Instructeur",
    course_icon: "Icône de la formation (FontAwesome)",
    add_module: "Ajouter un Module",
    add_lesson: "Ajouter une Leçon",
    edit_objective: "Modifier l'Objectif",
    create_objective: "Créer un Objectif",
    delete_objective: "Supprimer l'Objectif",
    add_key_result: "Ajouter un Résultat Clé",
    target: "Cible",
    unit: "Unité",
    current_value: "Actuel",
    create_contact: "Créer un Contact",
    edit_contact: "Modifier le Contact",
    delete_contact: "Supprimer le Contact",
    contact_name: "Nom du Contact",
    contact_company: "Société du Contact",
    contact_status: "Statut",
    lead: "Piste",
    contacted: "Contacté",
    prospect: "Prospect",
    customer: "Client",
    unreachable: "Non joignable",
    callback_expected: "Rappel / recontact attendu",
    crm_btn_contacted: "Contacté",
    crm_btn_unreachable: "Non joignable",
    crm_btn_callback: "Recontact attendu",
    crm_codification_hint:
      "Codification relance : « Contacté » = prise de contact réussie ; « Non joignable » = pas de joindre ; « Recontact attendu » = le client doit rappeler / à relancer (branchez webhooks ou automatisations dans Paramètres pour alertes et tâches).",
    pending_access_title: "Accès en attente de configuration",
    pending_access_body:
      "Votre compte est actif mais aucun module de département ne vous est encore attribué, ou vos droits n’ont pas été finalisés. Contactez votre super administrateur.",
    pipeline_view: "Pipeline",
    list_view: "Liste",
    grid_view: "Grille",
    compact_view: "Compact",
    sort_ascending: "Croissant",
    sort_descending: "Décroissant",
    view_label: "Vue",
    objective_found_singular: "objectif trouvé",
    objective_found_plural: "objectifs trouvés",
    project_found_singular: "projet trouvé",
    project_found_plural: "projets trouvés",
    for_search: "pour",
    work_email: 'E-mail Professionnel',
    personal_email: 'E-mail Personnel',
    office_phone: 'Téléphone Bureau',
    mobile_phone: 'Téléphone Portable',
    whatsapp_number: 'Numéro WhatsApp',
    assign_role: "Attribuer un Rôle",
    user_role: "Rôle de l'utilisateur",
    signup_role_label: "Rôle (fonction sur la plateforme)",
    signup_poste_note: "L'intitulé de poste pourra être renseigné dans votre profil par un administrateur.",
    poste_label: "Poste (intitulé)",
    ai_agent_title: 'COYA IA',
    ai_agent_placeholder: 'Posez-moi une question...',
    ai_agent_send: 'Envoyer',
    ai_agent_welcome_default: 'Bonjour! Comment puis-je vous aider aujourd\'hui ?',
    ai_agent_welcome_dashboard: 'Bienvenue sur votre tableau de bord ! Demandez-moi de trouver une section ou de résumer vos activités.',
    ai_agent_welcome_projects: "Dans Projets, je peux vous aider à imaginer des tâches, identifier des risques ou rédiger des plans. Qu'avez-vous en tête ?",
    ai_agent_welcome_goals_okrs: "Vous travaillez sur des objectifs ? Je peux vous aider à définir des Objectifs et Résultats Clés (OKRs). Demandez-moi comment !",
    ai_agent_welcome_courses: "Prêt à apprendre ? Demandez-moi de trouver une formation ou de suggérer un parcours d'apprentissage.",
    ai_agent_welcome_jobs: "En quête d'opportunités ? Je peux vous aider à trouver des emplois ou vous donner des conseils d'entretien.",
    ai_agent_welcome_knowledge_base: "Ceci est DOCS SENEGEL. Demandez-moi de trouver un fichier, de résumer un document ou de proposer une arborescence de dossiers.",
    ai_agent_welcome_crm_sales: "Dans le CRM, je peux vous aider à rédiger des e-mails ou suggérer des façons de gérer votre pipeline de ventes.",
    ai_agent_welcome_course_management: "Vous gérez des formations ? Je peux vous aider à structurer des modules ou créer des plans de cours.",
    ai_agent_welcome_analytics: "Ici, vous voyez les données de la plateforme. Demandez-moi d'expliquer un graphique.",
    ai_agent_welcome_user_management: "D'ici, vous pouvez gérer les utilisateurs. Je peux vous aider à comprendre les rôles et permissions.",
    ai_agent_welcome_settings: "Dans les Paramètres, gérez votre profil. Demandez-moi comment mettre à jour votre Passeport de Compétences.",
    ai_agent_welcome_leave_management: "Dans la Gestion des Congés, vous pouvez demander des congés ou gérer les demandes de l'équipe. Demandez-moi comment faire.",
    my_time_logs: "Mes Pointages",
    time_tracking_subtitle: "Consultez, gérez et planifiez votre temps pour toutes les activités.",
    total_time_logged: "Temps Total Pointé",
    duration_minutes: "Durée (minutes)",
    log_entry_for: "Pointage pour",
    no_time_logs_found: "Aucun pointage trouvé.",
    time_logged_today: "Temps Pointé Aujourd'hui",
    time_logged_this_week: "Temps Pointé Cette Semaine",
    new_log_entry: "Nouveau Pointage",
    select_type: "Sélectionner le type...",
    select_course: "Sélectionner une Formation",
    select_task_optional: "Sélectionner une Tâche (optionnel)",
    description: "Description",
    minutes: "minutes",
    view_time_logs: "Voir les Pointages",
    leave_management: "Demande de Congé",
    leave_management_subtitle: "Demandez et gérez vos demandes de congés.",
    manage_leaves: "Gérer les Congés",
    request_leave: "Demander un Congé",
    my_requests: "Mes Demandes",
    team_requests: "Demandes de l'Équipe",
    start_date: "Date de Début",
    end_date: "Date de Fin",
    reason: "Raison",
    submit_request: "Envoyer la Demande",
    approve: "Approuver",
    reject: "Rejeter",
    pending: "En attente",
    approved: "Approuvé",
    rejected: "Rejeté",
    no_leave_requests: "Aucune demande de congé trouvée.",
    team_availability: "Disponibilité de l'Équipe",
    upcoming_leaves: "Congés à Venir (7 prochains jours)",
    no_upcoming_leaves: "Aucun congé à venir.",
    signup_title: "Créez Votre Compte",
    signup_subtitle: "Rejoignez le futur de la productivité.",
    full_name: "Nom Complet",
    phone_number: "Numéro de Téléphone",
    password: "Mot de Passe",
    confirm_password: "Confirmer le Mot de Passe",
    signup_button: "S'inscrire",
    signup_prompt: "Vous n'avez pas de compte ? Inscrivez-vous",
    login_prompt: "Vous avez déjà un compte ? Connexion",
    login_highlight_roles_title: "Rôles & Accès",
    login_highlight_roles_description: "Certains rôles avancés peuvent nécessiter une invitation",
    login_error_generic: "Une erreur est survenue lors de la connexion. Veuillez réessayer.",
    login_error_invalid_credentials: "Identifiants invalides ou compte introuvable. Vérifiez votre email/mot de passe ou créez un nouveau compte.",
    login_error_account_not_found: "Ce compte n'existe pas ou a été supprimé. Vérifiez l'adresse email ou créez un compte.",
    login_error_wrong_password: "Mot de passe incorrect. Réessayez ou cliquez sur « Mot de passe oublié ? ».",
    login_error_email_not_confirmed: "Votre email doit être confirmé avant la connexion. Vérifiez votre boîte mail.",
    login_email_in_use_error: "Cet email est déjà utilisé. Utilisez un autre email ou connectez-vous.",
    login_unexpected_error: "Erreur inattendue lors de la connexion.",
    login_loading: "Connexion...",
    login_organization_loading: "Chargement des organisations…",
    login_organization_hint: "Choisissez votre organisation. Si elle n'existe pas, elle sera créée automatiquement après connexion (si autorisé).",
    login_organization_info_title: "Information",
    login_organization_info_line1: "Marque plateforme. SENEGEL reste l'organisation de référence pour les tests publics.",
    login_partner_org_label: "Organisations partenaires",
    login_organization_info_line2: "Accès sur invitation, créées par les Super Administrateurs.",
    login_reset_success: "Un lien de réinitialisation a été envoyé à votre e-mail.",
    login_reset_error: "Erreur lors de l'envoi du lien.",
    login_reset_title: "Réinitialiser le mot de passe",
    login_reset_cancel: "Annuler",
    login_reset_send: "Envoyer le lien",
    login_reset_sending: "Envoi...",
    signup_hero_tagline: "Créer des opportunités pour la jeunesse en Afrique",
    signup_hero_subtagline: "Plateforme intelligente multi-organisations",
    signup_highlight_multi_org_title: "Multi-Organisations",
    signup_highlight_multi_org_description: "Chaque organisation dispose de son espace sécurisé",
    signup_highlight_unified_title: "Écosystème Unifié",
    signup_highlight_unified_description: "Une plateforme, plusieurs organisations, des milliers d'utilisateurs",
    signup_highlight_security_title: "Sécurité & Isolation",
    signup_highlight_security_description: "Vos données restent isolées au sein de votre organisation",
    signup_role_group_management: "Gestion",
    signup_role_group_pedagogy: "Pédagogique & Facilitation",
    signup_role_group_youth: "Jeunesse & Académique",
    signup_role_group_entrepreneurship: "Entrepreneuriat & Partenariats",
    signup_role_group_creative: "Créatif & Médias",
    signup_role_group_partners: "Facilitateurs partenaires",
    signup_role_group_super_admin: "Super Administration",
    signup_organization_label: "Organisation",
    signup_organization_placeholder: "Ex : SENEGEL ou Partenaire ABC",
    signup_organization_hint: "SENEGEL par défaut. Si l'organisation partenaire n'existe pas encore, elle sera créée automatiquement.",
    signup_banner_title: "Création de compte",
    signup_banner_description_prefix: "Vous créez un compte dans",
    signup_banner_description_suffix: "Choisissez le rôle qui correspond à vos responsabilités.",
    signup_banner_all_roles_label: "Tous les rôles disponibles",
    signup_banner_all_roles_description: "Choisissez parmi tous les rôles du MVP (administrator, manager, supervisor, trainer, student, entrepreneur, etc.).",
    signup_banner_note_label: "Note",
    signup_banner_note_description: "Le rôle super_administrator est réservé et ne peut être créé que par un Super Administrateur existant.",
    signup_full_name_placeholder: "Votre nom complet",
    signup_email_placeholder: "votre@email.com",
    signup_email_domain_warning: "⚠️ Certains domaines peuvent être bloqués. Utilisez un email valide (Gmail, Outlook, etc.)",
    signup_phone_placeholder: "+221 XX XXX XX XX",
    signup_hide_password: "Masquer le mot de passe",
    signup_show_password: "Afficher le mot de passe",
    signup_hide_confirm_password: "Masquer la confirmation du mot de passe",
    signup_show_confirm_password: "Afficher la confirmation du mot de passe",
    signup_loading: "Création du compte...",
    signup_role_requires_validation_message: "Ce rôle nécessite une validation par un Super Administrateur. Votre compte restera en attente jusqu'à approbation.",
    signup_all_roles_card_title: "Tous les rôles disponibles",
    signup_all_roles_card_description: "Créez un compte avec n'importe quel rôle selon vos besoins. Chaque rôle possède ses propres permissions et accès.",
    signup_roles_management_label: "Rôles de gestion :",
    signup_roles_pedagogy_label: "Rôles pédagogiques & facilitation :",
    signup_roles_youth_label: "Jeunesse & académique :",
    signup_roles_entrepreneurship_label: "Entrepreneuriat & partenariats :",
    signup_roles_creative_label: "Créatif & médias :",
    signup_roles_partner_label: "Facilitateurs partenaires :",
    signup_roles_super_admin_label: "Super administration :",
    signup_roles_note_text: "Note : Les rôles de gestion avancés (administrator, manager, supervisor, trainer, coach, facilitator, mentor, partner_facilitator et super_administrator) nécessitent la validation d'un Super Administrateur.",
    signup_role_status_validation: "Validation requise",
    signup_role_status_allowed: "Inscription autorisée",
    signup_role_status_validation_message: "Votre demande pour le rôle {role} sera examinée par un Super Administrateur avant activation.",
    signup_role_status_allowed_message: "Vous pouvez créer un compte avec le rôle {role}. Vos permissions seront appliquées immédiatement.",
    signup_error_generic: "Une erreur est survenue lors de l'inscription. Veuillez réessayer.",
    signup_error_email_exists: "Cet email est déjà enregistré. Connectez-vous ou utilisez un autre email.",
    signup_error_invalid_email: "Adresse email invalide. Vérifiez le format ou utilisez un autre domaine.",
    signup_error_password_short: "Mot de passe trop court. Utilisez au moins 8 caractères avec des lettres et des chiffres.",
    signup_password_min_length: "Le mot de passe doit contenir au moins 8 caractères.",
    signup_role_unavailable: 'Le rôle "{role}" n\'est plus disponible. Un autre compte l\'utilise déjà.',
    signup_email_in_use_detailed: "Cet email est déjà utilisé. Utilisez un autre email ou connectez-vous.",
    signup_invalid_email_hint: "Email invalide. Veuillez utiliser un email valide (ex : votrenom@gmail.com).",
    passwords_do_not_match: "Les mots de passe ne correspondent pas.",
    email_in_use: "Cet e-mail est déjà utilisé.",
    login_title: "Content de vous revoir !",
    login_subtitle: "Optimisez votre flux de travail, en toute sécurité.",
    forgot_password: "Mot de passe oublié ?",
    need_help: "Besoin d'aide ?",
    auth_ai_assistant_title: "Assistant IA d'Authentification",
    password_strength: "Force du mot de passe",
    strength_weak: "Faible",
    strength_medium: "Moyen",
    strength_strong: "Fort",
    strength_very_strong: "Très fort",
    auth_ai_prompt_roles: "Quelle est la différence entre les rôles ?",
    auth_ai_prompt_password: "J'ai oublié mon mot de passe. Que faire ?",
    estimated_time_short: "Est. (h)",
    logged_time_short: "Pointé (h)",
    finance: "Finance",
    finance_title: "Rationaliser les Opérations Financières et Optimiser la Rentabilité",
    finance_subtitle: "Une gestion financière rigoureuse est le fondement de la stabilité et de la croissance. Le module Finance centralise toutes vos opérations financières, simplifiant la gestion des flux de trésorerie et le suivi des dépenses.",
    finance_partial_payment_amount_required: "Veuillez saisir un montant payé valide pour un paiement partiel.",
    finance_partial_payment_must_be_less_total: "Le montant payé doit être inférieur au montant total. Passez le statut à « Payé » si la facture est complètement réglée.",
    finance_partial_payment_cannot_exceed_total: "Le montant payé ne peut pas dépasser le montant total de la facture.",
    finance_paid_amount_placeholder: "Ex : 1500",
    finance_total_amount_label: "Montant total",
    finance_amount_remaining_label: "Reste à payer",
    view_finance: "Voir les Finances",
    invoices: "Factures",
    expenses: "Dépenses",
    recurring: "Récurrent",
    budgets: "Budgets",
    new_invoice: "Nouvelle Facture",
    new_expense: "Nouvelle Dépense",
    new_budget: "Nouveau Budget",
    total_revenue: "Revenu Total",
    total_expenses: "Dépenses Totales",
    net_income: "Revenu Net",
    total_outstanding_invoices: "Factures Impayées",
    total_due_expenses: "Dépenses Dues",
    average_payment_time: "Temps Paiement Moy.",
    days: "jours",
    overdue: "En Retard",
    invoice_number: "Facture n°",
    client_name: "Nom du Client",
    amount: "Montant",
    draft: "Brouillon",
    sent: "Envoyée",
    paid: "Payée",
    partially_paid: "Partiellement Payée",
    paid_amount: "Montant Payé",
    unpaid: "Impayée",
    category: "Catégorie",
    date: "Date",
    create_invoice: "Créer une Facture",
    edit_invoice: "Modifier la Facture",
    create_expense: "Créer une Dépense",
    edit_expense: "Modifier la Dépense",
    delete_invoice: "Supprimer la Facture",
    delete_expense: "Supprimer la Dépense",
    receipt: "Reçu",
    upload_receipt: "Télécharger un reçu",
    download_receipt: "Télécharger le reçu",
    view_receipt: "Voir le reçu",
    no_receipt_attached: "Aucun reçu",
    payable_by: "Payable avant le",
    remove_receipt: "Retirer",
    evidence_documents: "Documents de Preuve",
    upload_evidence: "Télécharger une Preuve",
    download_evidence: "Télécharger la Preuve",
    no_evidence_uploaded: "Aucune preuve téléchargée.",
    remove_evidence: "Retirer",
    notifications: "Notifications",
    no_notifications: "Aucune nouvelle notification",
    reminder_settings: "Paramètres des rappels",
    remind_days_before: "Me rappeler (jours avant l'échéance)",
    invoice_due_reminder: "La facture {invoiceNumber} est due le {dueDate}.",
    expense_due_reminder: "La dépense pour '{description}' est payable le {dueDate}.",
    mark_as_read: "Marquer comme lu",
    clear_all: "Tout effacer",
    make_recurring: "Rendre récurrent ?",
    frequency: "Fréquence",
    monthly: "Mensuel",
    quarterly: "Trimestriel",
    annually: "Annuel",
    end_date_optional: "Date de fin (Optionnel)",
    recurring_invoices: "Factures Récurrentes",
    recurring_expenses: "Dépenses Récurrentes",
    next_due_date: "Prochaine Échéance",
    new_recurring_invoice: "Nouvelle Facture Récurrente",
    new_recurring_expense: "Nouvelle Dépense Récurrente",
    finance_invoice_found_singular: "facture trouvée",
    finance_invoice_found_plural: "factures trouvées",
    finance_expense_found_singular: "dépense trouvée",
    finance_expense_found_plural: "dépenses trouvées",
    finance_no_invoice_match: "Aucune facture ne correspond aux critères",
    finance_no_invoice: "Aucune facture",
    finance_no_expense_match: "Aucune dépense ne correspond aux critères",
    finance_no_expense: "Aucune dépense",
    finance_partial_payment_constraint_error: "❌ ERREUR : Impossible de créer une facture « Partiellement payé ».\n\n🔧 ACTION REQUISE (2 minutes) :\n1. Aller sur https://supabase.com/dashboard\n2. Ouvrir « SQL Editor » → « New query »\n3. Coller le script depuis docs/ACTIVER-PAIEMENT-PARTIEL.md\n4. Cliquer sur « Run »\n5. Recharger cette page et réessayer.",
    finance_save_invoice_error: "Erreur lors de la sauvegarde de la facture. Veuillez réessayer.",
    finance_currency_field_label: "Devise",
    finance_transaction_date: "Date de transaction",
    finance_use_manual_rate: "Utiliser un taux de change manuel",
    finance_manual_exchange_rate: "Taux de change vers USD",
    finance_manual_rate_help: "Laissez vide pour utiliser le taux automatique de l'API",
    goal_title_required: "Le titre de l'objectif est requis.",
    goal_key_result_title_required: "Chaque Key Result doit avoir un titre.",
    goal_key_result_target_positive: "La cible d'un Key Result doit être supérieure à 0.",
    goal_key_result_current_range: "La valeur actuelle d'un Key Result doit être comprise entre 0 et la cible.",
    goal_select_project: "Sélectionner un projet",
    goal_missing_id_error: "Erreur : impossible de mettre à jour l'objectif car l'ID est manquant.",
    goal_generate_error: "Erreur lors de la génération des OKRs. Veuillez réessayer.",
    project_permission_error: "Vous n'êtes pas autorisé à modifier ou supprimer ce projet.",
    project_title_required: "Le titre du projet est requis.",
    project_description_required: "La description du projet est requise.",
    project_due_date_invalid: "La date d'échéance ne peut pas être dans le passé.",
    project_missing_id_error: "Erreur : impossible de mettre à jour le projet car l'ID est manquant.",
    create_budget: "Créer un Budget",
    edit_budget: "Modifier le Budget",
    delete_budget: "Supprimer le Budget",
    budget_title: "Titre du Budget",
    budget_type: "Type de Budget",
    project_budget: "Budget de Projet",
    office_management: "Gestion de Bureau",
    total_budget: "Budget Total",
    amount_spent: "Montant Dépensé",
    remaining: "Restant",
    link_to_budget: "Lier à un Budget (Optionnel)",
    link_to_budget_help: "Lier cette dépense à un poste de budget pour suivre les dépenses par rapport au budget prévu.",
    optional: "Optionnel",
    no_budget: "Pas de Budget",
    view_details: "Voir les détails",
    view_entity: "Voir l'entité",
    action_details: "Détails de l'action",
    summary: "Résumé",
    changes: "Modifications",
    before: "Avant",
    after: "Après",
    other_metadata: "Autres métadonnées",
    no_history: "Aucune activité enregistrée.",
    loading: "Chargement...",
    load_more: "Charger plus",
    system: "Système",
    yes: "Oui",
    no: "Non",
    activity_history: "Historique des activités",
    activity_history_subtitle: "Suivi complet des actions réalisées dans la plateforme.",
    all_modules: "Tous les modules",
    all_actions: "Toutes les actions",
    budget_lines: "Lignes Budgétaires",
    add_budget_line: "Ajouter une Ligne",
    add_budget_item: "Ajouter un Poste",
    item_description: "Description du Poste",
    planned_amount: "Prévu",
    actual_spent: "Dépensé",
    calendar_and_meetings: "Calendrier & Réunions",
    schedule_meeting: "Planifier une réunion",
    new_meeting: "Nouvelle Réunion",
    edit_meeting: "Modifier la Réunion",
    delete_meeting: "Supprimer la Réunion",
    meeting_title: "Titre de la Réunion",
    start_time: "Heure de début",
    end_time: "Heure de fin",
    attendees: "Participants",
    meeting_details: "Détails de la Réunion",
    log_time_for_meeting: "Pointer pour cette réunion",
    no_meetings_today: "Aucune réunion prévue pour ce jour.",
    today: "Aujourd'hui",
    previous_week: "Semaine Précédente",
    next_week: "Semaine Suivante",
    image_editing: "Édition d'Image",
    upload_image_to_edit: "Téléchargez une image pour commencer",
    editing_prompt_placeholder: "ex: Donner à cette photo l'aspect d'une peinture à l'aquarelle",
    generate_edit: "Générer la Modification",
    original_image: "Image Originale",
    edited_image: "Image Modifiée",
    remove_image: "Retirer l'Image",
    download_image: "Télécharger l'Image",
    project_saved: "Projet enregistré avec succès.",
    invoice_saved: "Facture enregistrée avec succès.",
    expense_saved: "Dépense enregistrée avec succès.",
    contact_saved: "Contact enregistré avec succès.",
    item_deleted: "Élément supprimé.",
    project_status_overview: "Aperçu du Statut des Projets",
    proactive_ai_suggestion_tasks: "Besoin d'aide pour trouver des tâches pour votre nouveau projet ?",
    proactive_ai_suggestion_overdue: "Je peux aider à rédiger un rappel pour vos factures en retard.",
    status_selector_title: "Choisissez votre statut",
    status_selector_subtitle: "Ce statut sera enregistré et pourra être modifié depuis le tableau de bord. Le temps n'est comptabilisé que lorsque vous n'êtes pas absent.",
    status_selector_skip_next: "Ne plus demander à chaque connexion",
    status_selector_confirm: "Entrer sur la plateforme",
    status_present: "Présent / En ligne",
    status_absent: "Absent",
    status_pause_coffee: "Pause café",
    status_pause_lunch: "Pause déjeuner",
    status_in_meeting: "En réunion",
    status_away_mission: "Absent / Mission externe",
    status_brief_team: "Point d'équipe",
    status_technical_issue: "Problème technique",
    status_timer_today: "Aujourd'hui",
    status_not_counted: "Temps non comptabilisé (absent)",
    status_selector_modal_message: "Merci de choisir le statut convenant pour continuer. Vous pourrez le modifier à tout moment depuis le tableau de bord.",
    status_selector_help: "Aide",
    status_selector_help_title: "Guide des statuts",
    status_help_intro: "Choisissez le statut qui correspond à votre activité. Le temps n'est comptabilisé que si vous n'êtes pas absent.",
    status_help_present: "Vous êtes au travail et disponible.",
    status_help_absent: "Vous n'êtes pas en activité ; le temps n'est pas compté.",
    status_help_pause_coffee: "Pause courte (ex. café).",
    status_help_pause_lunch: "Pause déjeuner.",
    status_help_in_meeting: "En réunion ou en appel.",
    status_help_away_mission: "Hors bureau (mission externe, déplacement).",
    status_help_brief_team: "Point d'équipe ou stand-up.",
    status_help_technical_issue: "Problème technique (IT, connexion, etc.).",
    current_status: "Statut actuel",
    change_status: "Changer",
    no_presence_session: "Aucune session en cours",
    profile_photo_upload: "Changer la photo de profil",
    profile_photo_uploaded: "Photo mise à jour.",
    demo_next: "Suivant",
    demo_prev: "Retour",
    demo_pause: "Pause",
    demo_auto: "Démo auto",
    demo_close: "Fermer",
    demo_step_intro: "Votre statut détermine si votre temps est compté. Choisissez celui qui correspond à votre activité.",
    demo_step_of: "sur",
  },
};
